stage: pt
model_name_or_path: /mnt/local/jyhu/llm_assets/models/chatglm2-6b 
do_train: true
dataset: Ihin_pretrain
dataset_dir: /mnt/local/jyhu/llm_assets/dataset/Ihin_AW 
template: chatglm2
finetuning_type: lora
lora_target: query_key_value
output_dir: /mnt/local/jyhu/LLM-Train/outputs/Ihin_AW/Ihin_AW_v1.2/pt-chatglm2 
overwrite_cache: true
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
lr_scheduler_type: cosine
logging_steps: 10
save_steps: 100
learning_rate: 0.00005 # 5e-5
num_train_epochs: 20
plot_loss: true
fp16: true
evaluation_strategy: steps
load_best_model_at_end: true
preprocessing_num_workers: 32
val_size: 0.001
# max_samples: 200000