stage: sft
model_name_or_path: /mnt/eye_team/jyhu/Ihin_assets/share/Ihin-v1-2
do_predict: true
dataset: Ihin_test
dataset_dir: /mnt/eye_team/jyhu/Ihin_assets/Ihin_dataset_v1.2
template: chatglm2
finetuning_type: lora
output_dir: outputs/Ihin/Ihin_v1.2/sft-chatglm2
per_device_eval_batch_size: 8
predict_with_generate: true