stage: sft
model_name_or_path: /mnt/local/jyhu/llm_assets/models/chatglm3-6b
checkpoint_dir: /mnt/local/jyhu/LLM-Train/outputs/retina_gpt/sft-chatglm3/checkpoint-2000
do_predict: true
dataset: huatuo_encyclopedia_test
dataset_dir: /mnt/local/jyhu/llm_assets/dataset/Retina_GPT
template: chatglm3
finetuning_type: lora
output_dir: /mnt/local/jyhu/LLM-Train/outputs/retina_gpt/sft-chatglm3
per_device_eval_batch_size: 8
predict_with_generate: true