stage: sft
model_name_or_path: /mnt/local/jyhu/llm_assets/models/Yi-34B-Chat
# adapter_name_or_path: /mnt/local/jyhu/LLaMA-Efficient-Tuning/outputs/retina_gpt/sft-yi-34b-chat/checkpoint-8000
do_predict: true
dataset: huatuo_encyclopedia_test
dataset_dir: /mnt/local/jyhu/llm_assets/dataset/Retina_GPT
template: yi
finetuning_type: lora
output_dir: /mnt/local/jyhu/LLaMA-Efficient-Tuning/outputs/retina_gpt/sft-yi-34b-chat
per_device_eval_batch_size: 8
predict_with_generate: true