CUDA_VISIBLE_DEVICES=0,1,2,3 accelerate launch src/train_bash.py \
    --stage sft \
    --model_name_or_path Llama-2-7b-chat-hf \
    --do_train \
    --dataset ft_train \
    --dataset_dir data/medicalgpt \
    --finetuning_type lora \
    --output_dir outputs/output-sft-llama2  \
    --overwrite_cache \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 2.0 \
    --plot_loss \
    --fp16 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --dev_ratio 0.001 \
    --preprocessing_num_workers 32 \
    --max_samples 200000 \