stage: sft
model_name_or_path: /mnt/local/jyhu/llm_assets/models/chatglm2-6b 
# checkpoint_dir: ../outputs/retina_gpt/pt-chatglm2/checkpoint-15500
template: chatglm2
do_train: true
dataset: self_cognition
dataset_dir: /mnt/local/jyhu/llm_assets/dataset/Retina_GPT
finetuning_type: lora
lora_target: query_key_value
output_dir: /mnt/local/jyhu/LLM-Train/outputs/retina_gpt/sft-chatglm2
overwrite_cache: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
lr_scheduler_type: cosine
logging_steps: 10
save_steps: 100
learning_rate: 0.00005 # 5e-5
num_train_epochs: 20.0
plot_loss: true
fp16: true
evaluation_strategy: steps
load_best_model_at_end: true
val_size: 0.001
preprocessing_num_workers: 32
# max_samples: 200000